use crate::span::Span;

/// A single lexeme with its source span.
#[derive(Debug, Clone, PartialEq)]
pub struct Token {
    pub kind: TokenKind,
    pub span: Span,
}

impl Token {
    pub fn new(kind: TokenKind, span: Span) -> Self {
        Self { kind, span }
    }
}

/// Decoded token kinds for the LeetCode C++ subset.
#[derive(Debug, Clone, PartialEq)]
pub enum TokenKind {
    Ident(String),
    Keyword(Keyword),
    IntLit {
        value: u128,
        suffix: IntSuffix,
        base: IntBase,
    },
    FloatLit {
        value: f64,
        suffix: FloatSuffix,
    },
    CharLit(char),
    StringLit(String),
    Punct(Punct),
    Eof,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum IntBase {
    Decimal,
    Hex,
    Binary,
    Octal,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default)]
pub enum IntSuffix {
    #[default]
    None,
    U,
    L,
    Ul,
    Ll,
    Ull,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default)]
pub enum FloatSuffix {
    #[default]
    None,
    F,
    L,
}

/// Keywords recognized by the lexer.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Keyword {
    Alignas,
    Alignof,
    Auto,
    Bool,
    Break,
    Case,
    Catch,
    Char,
    Class,
    Const,
    Constexpr,
    Continue,
    Decltype,
    Default,
    Delete,
    Do,
    Double,
    Else,
    Enum,
    Explicit,
    Extern,
    False,
    Float,
    For,
    Friend,
    Goto,
    If,
    Inline,
    Int,
    Long,
    Mutable,
    Namespace,
    New,
    Noexcept,
    Nullptr,
    Operator,
    Private,
    Protected,
    Public,
    Register,
    ReinterpretCast,
    Return,
    Short,
    Signed,
    Sizeof,
    Static,
    StaticAssert,
    StaticCast,
    Struct,
    Switch,
    Template,
    This,
    Throw,
    True,
    Try,
    Typedef,
    Typeid,
    Typename,
    Union,
    Unsigned,
    Using,
    Virtual,
    Void,
    Volatile,
    WcharT,
    While,
    Override,
    Final,
}

impl Keyword {
    /// Map an identifier spelling to a keyword, if it is one.
    pub fn from_str(s: &str) -> Option<Self> {
        Some(match s {
            "alignas" => Self::Alignas,
            "alignof" => Self::Alignof,
            "auto" => Self::Auto,
            "bool" => Self::Bool,
            "break" => Self::Break,
            "case" => Self::Case,
            "catch" => Self::Catch,
            "char" => Self::Char,
            "class" => Self::Class,
            "const" => Self::Const,
            "constexpr" => Self::Constexpr,
            "continue" => Self::Continue,
            "decltype" => Self::Decltype,
            "default" => Self::Default,
            "delete" => Self::Delete,
            "do" => Self::Do,
            "double" => Self::Double,
            "else" => Self::Else,
            "enum" => Self::Enum,
            "explicit" => Self::Explicit,
            "extern" => Self::Extern,
            "false" => Self::False,
            "float" => Self::Float,
            "for" => Self::For,
            "friend" => Self::Friend,
            "goto" => Self::Goto,
            "if" => Self::If,
            "inline" => Self::Inline,
            "int" => Self::Int,
            "long" => Self::Long,
            "mutable" => Self::Mutable,
            "namespace" => Self::Namespace,
            "new" => Self::New,
            "noexcept" => Self::Noexcept,
            "nullptr" => Self::Nullptr,
            "operator" => Self::Operator,
            "private" => Self::Private,
            "protected" => Self::Protected,
            "public" => Self::Public,
            "register" => Self::Register,
            "reinterpret_cast" => Self::ReinterpretCast,
            "return" => Self::Return,
            "short" => Self::Short,
            "signed" => Self::Signed,
            "sizeof" => Self::Sizeof,
            "static" => Self::Static,
            "static_assert" => Self::StaticAssert,
            "static_cast" => Self::StaticCast,
            "struct" => Self::Struct,
            "switch" => Self::Switch,
            "template" => Self::Template,
            "this" => Self::This,
            "throw" => Self::Throw,
            "true" => Self::True,
            "try" => Self::Try,
            "typedef" => Self::Typedef,
            "typeid" => Self::Typeid,
            "typename" => Self::Typename,
            "union" => Self::Union,
            "unsigned" => Self::Unsigned,
            "using" => Self::Using,
            "virtual" => Self::Virtual,
            "void" => Self::Void,
            "volatile" => Self::Volatile,
            "wchar_t" => Self::WcharT,
            "while" => Self::While,
            "override" => Self::Override,
            "final" => Self::Final,
            _ => return None,
        })
    }

    pub fn as_str(self) -> &'static str {
        match self {
            Self::Alignas => "alignas",
            Self::Alignof => "alignof",
            Self::Auto => "auto",
            Self::Bool => "bool",
            Self::Break => "break",
            Self::Case => "case",
            Self::Catch => "catch",
            Self::Char => "char",
            Self::Class => "class",
            Self::Const => "const",
            Self::Constexpr => "constexpr",
            Self::Continue => "continue",
            Self::Decltype => "decltype",
            Self::Default => "default",
            Self::Delete => "delete",
            Self::Do => "do",
            Self::Double => "double",
            Self::Else => "else",
            Self::Enum => "enum",
            Self::Explicit => "explicit",
            Self::Extern => "extern",
            Self::False => "false",
            Self::Float => "float",
            Self::For => "for",
            Self::Friend => "friend",
            Self::Goto => "goto",
            Self::If => "if",
            Self::Inline => "inline",
            Self::Int => "int",
            Self::Long => "long",
            Self::Mutable => "mutable",
            Self::Namespace => "namespace",
            Self::New => "new",
            Self::Noexcept => "noexcept",
            Self::Nullptr => "nullptr",
            Self::Operator => "operator",
            Self::Private => "private",
            Self::Protected => "protected",
            Self::Public => "public",
            Self::Register => "register",
            Self::ReinterpretCast => "reinterpret_cast",
            Self::Return => "return",
            Self::Short => "short",
            Self::Signed => "signed",
            Self::Sizeof => "sizeof",
            Self::Static => "static",
            Self::StaticAssert => "static_assert",
            Self::StaticCast => "static_cast",
            Self::Struct => "struct",
            Self::Switch => "switch",
            Self::Template => "template",
            Self::This => "this",
            Self::Throw => "throw",
            Self::True => "true",
            Self::Try => "try",
            Self::Typedef => "typedef",
            Self::Typeid => "typeid",
            Self::Typename => "typename",
            Self::Union => "union",
            Self::Unsigned => "unsigned",
            Self::Using => "using",
            Self::Virtual => "virtual",
            Self::Void => "void",
            Self::Volatile => "volatile",
            Self::WcharT => "wchar_t",
            Self::While => "while",
            Self::Override => "override",
            Self::Final => "final",
        }
    }
}

/// Punctuation and operators (maximal-munch spellings).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Punct {
    // Single
    LBrace,
    RBrace,
    LBracket,
    RBracket,
    LParen,
    RParen,
    Semi,
    Colon,
    Comma,
    Dot,
    Question,
    Tilde,
    Not,
    Hash,
    // Multi / ops
    Plus,
    Minus,
    Star,
    Slash,
    Percent,
    Caret,
    Amp,
    Pipe,
    Eq,
    Lt,
    Gt,
    PlusPlus,
    MinusMinus,
    Arrow,
    ArrowStar,
    DotStar,
    Scope,
    LtLt,
    GtGt,
    LtEq,
    GtEq,
    EqEq,
    NotEq,
    AmpAmp,
    PipePipe,
    PlusEq,
    MinusEq,
    StarEq,
    SlashEq,
    PercentEq,
    CaretEq,
    AmpEq,
    PipeEq,
    LtLtEq,
    GtGtEq,
    Ellipsis,
}

impl Punct {
    pub fn as_str(self) -> &'static str {
        match self {
            Self::LBrace => "{",
            Self::RBrace => "}",
            Self::LBracket => "[",
            Self::RBracket => "]",
            Self::LParen => "(",
            Self::RParen => ")",
            Self::Semi => ";",
            Self::Colon => ":",
            Self::Comma => ",",
            Self::Dot => ".",
            Self::Question => "?",
            Self::Tilde => "~",
            Self::Not => "!",
            Self::Hash => "#",
            Self::Plus => "+",
            Self::Minus => "-",
            Self::Star => "*",
            Self::Slash => "/",
            Self::Percent => "%",
            Self::Caret => "^",
            Self::Amp => "&",
            Self::Pipe => "|",
            Self::Eq => "=",
            Self::Lt => "<",
            Self::Gt => ">",
            Self::PlusPlus => "++",
            Self::MinusMinus => "--",
            Self::Arrow => "->",
            Self::ArrowStar => "->*",
            Self::DotStar => ".*",
            Self::Scope => "::",
            Self::LtLt => "<<",
            Self::GtGt => ">>",
            Self::LtEq => "<=",
            Self::GtEq => ">=",
            Self::EqEq => "==",
            Self::NotEq => "!=",
            Self::AmpAmp => "&&",
            Self::PipePipe => "||",
            Self::PlusEq => "+=",
            Self::MinusEq => "-=",
            Self::StarEq => "*=",
            Self::SlashEq => "/=",
            Self::PercentEq => "%=",
            Self::CaretEq => "^=",
            Self::AmpEq => "&=",
            Self::PipeEq => "|=",
            Self::LtLtEq => "<<=",
            Self::GtGtEq => ">>=",
            Self::Ellipsis => "...",
        }
    }
}

impl TokenKind {
    /// Short spelling for diagnostics (`found …`).
    pub fn describe(&self) -> String {
        match self {
            Self::Ident(s) => format!("identifier `{s}`"),
            Self::Keyword(k) => format!("`{}`", k.as_str()),
            Self::IntLit { .. } => "integer literal".into(),
            Self::FloatLit { .. } => "float literal".into(),
            Self::CharLit(_) => "character literal".into(),
            Self::StringLit(_) => "string literal".into(),
            Self::Punct(p) => format!("`{}`", p.as_str()),
            Self::Eof => "end of file".into(),
        }
    }
}
